### ISSUE TITLE
Hourly Pricing Data

### ISSUE THREAD

**Issue by FayzulSaimun** [CPES-Power-and-Energy-Systems/ewh-flex#1]
Hi,  I was trying to use this for my EWH; however, I have hourly pricing data. Is it possible to use each hour's pricing data instead of a fixed tariff?

**Comment by zepedropaulos** [comment]
Thanks for your input, @FayzulSaimun. At this moment, the tool only accepts data from both simple or dual tariffs (i.e., same tariff for the whole day + daily tariff, or dual tariff for day/night + daily tariff). We can probably add the option for hourly pricing, but I have some questions:

- Is the pricing dynamic or static by day (i.e., changes each hour with the same pattern for each day, or also varies per day)? The former can require the user to provide a full pricing JSON/CSV, but the latter requires only filling in 24 slots of pricing. 
- That pricing mechanism includes any daily access tariff?

While this feature is not yet implemented, you can test the tool disregarding costs (by selecting simple tariff, for example), and optimize the usage of the EWH based only on the consumption data. For a **rough** estimation of cost savings, I suggest applying the hourly tariff to the output usage/energy file directly.

**Comment by FayzulSaimun** [comment]
@zepedropaulos  Thank you for the quick response. To answer your questions:

1. Yes, the pricing is dynamic. Pricing varies every hour and every day. 
2. There is no daily tariff mechanism included in the energy pricing.

I will try now with EWH uses and then will apply the hourly pricing to it.

**Comment by zepedropaulos** [comment]
@FayzulSaimun I just updated the code in order to add dynamic pricing options. In the GUI, you should now have the option to "upload" a princing JSON/CSV with the prices. Bear in mind that, in the current version, the provided file should have the same length and resolution as the provided EWH Load JSON/CSV.

**Comment by itsjrsa** [comment]
Thanks for the feedback @zepedropaulos! The issue has been addressed. 
Feel free to reopen if needed.
